--- #YAML:1.0
name:                XML-Rewrite
version:             0.10
abstract:            modify XML data
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::Compile:                  0.92
    XML::Compile::Cache:           0.13
    XML::Compile::Tester:          0.01
    XML::LibXML:                   1.65
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
